AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# This is a weird gem. This is fine here :)
Naming/FileName:
  Exclude:
    - 'lib/sonic-pi-akai-apc-mini.rb'
    - 'spec/sonic-pi-akai-apc-mini_spec.rb'
